// Generated by tools/signalFixtures.test.mjs from src/client/haptics/scenarios.ts.
// Do not edit; run the tests with UPDATE_FIXTURES=1 instead.
import type { FixtureScenario } from './types';

export const SCENARIOS: readonly FixtureScenario[] = [
  {
    "name": "swipe-landed",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1000,
          "id": "blade-torso",
          "phase": "start",
          "value": 0.3,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1033,
          "id": "blade-torso",
          "phase": "update",
          "value": 0.9,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1050,
          "id": "blade-torso",
          "phase": "end",
          "value": 0.6,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_hit",
        "t": 1080
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1080,
          "magnitude": 0.42857142857142855,
          "valence": "good",
          "importance": 0.5,
          "actor": "self",
          "target": "other",
          "outcome": "landed",
          "description": "player slashes enemy torso with paper sword",
          "gauges": [
            "enemy_guard",
            "enemy_health"
          ],
          "sound": "hit_sword",
          "base": "enemy_hit",
          "chain": {
            "id": "swipe-1",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1080,
          "id": "enemy_guard",
          "value": 0.9,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1080,
          "id": "enemy_health",
          "value": 0.8,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      }
    ]
  },
  {
    "name": "swipe-heavy-weak-point",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1000,
          "id": "blade-head",
          "phase": "start",
          "value": 0.3,
          "description": "player paper sword crosses enemy head",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1033,
          "id": "blade-head",
          "phase": "update",
          "value": 0.9,
          "description": "player paper sword crosses enemy head",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1050,
          "id": "blade-head",
          "phase": "end",
          "value": 0.6,
          "description": "player paper sword crosses enemy head",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_hit",
        "t": 1090
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1090,
          "magnitude": 1,
          "valence": "good",
          "importance": 0.7,
          "actor": "self",
          "target": "other",
          "outcome": "landed",
          "description": "player heavily smashes enemy head with paper hammer",
          "gauges": [
            "enemy_guard",
            "enemy_health"
          ],
          "sound": "hit_hammer",
          "base": "enemy_hit",
          "chain": {
            "id": "swipe-1",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1090,
          "id": "enemy_health",
          "value": 0.4,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      }
    ]
  },
  {
    "name": "swipe-kill",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 0.1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1000,
          "id": "blade-head",
          "phase": "start",
          "value": 0.3,
          "description": "player paper sword crosses enemy head",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1033,
          "id": "blade-head",
          "phase": "update",
          "value": 0.9,
          "description": "player paper sword crosses enemy head",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1050,
          "id": "blade-head",
          "phase": "end",
          "value": 0.6,
          "description": "player paper sword crosses enemy head",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_hit",
        "t": 1080
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1080,
          "magnitude": 0.6428571428571429,
          "valence": "good",
          "importance": 0.7,
          "actor": "self",
          "target": "other",
          "outcome": "landed",
          "description": "player slashes enemy head with paper sword",
          "gauges": [
            "enemy_guard",
            "enemy_health"
          ],
          "sound": "hit_sword",
          "base": "enemy_hit",
          "chain": {
            "id": "swipe-1",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_kill",
        "t": 1080
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1080,
          "magnitude": 0.6,
          "valence": "good",
          "importance": 0.8,
          "actor": "self",
          "target": "other",
          "outcome": "broke",
          "description": "player fells the enemy",
          "gauges": [
            "enemy_health"
          ],
          "sound": "felled",
          "base": "enemy_kill",
          "chain": {
            "id": "swipe-1",
            "step": "end"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1080,
          "id": "enemy_health",
          "value": 0,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      }
    ]
  },
  {
    "name": "swipe-boss-kill",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 0.05,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1000,
          "id": "blade-torso",
          "phase": "start",
          "value": 0.3,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1033,
          "id": "blade-torso",
          "phase": "update",
          "value": 0.9,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1050,
          "id": "blade-torso",
          "phase": "end",
          "value": 0.6,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_hit",
        "t": 1080
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1080,
          "magnitude": 0.7142857142857143,
          "valence": "good",
          "importance": 0.5,
          "actor": "self",
          "target": "other",
          "outcome": "landed",
          "description": "player heavily slashes enemy torso with paper sword",
          "gauges": [
            "enemy_guard",
            "enemy_health"
          ],
          "sound": "hit_sword",
          "base": "enemy_hit",
          "chain": {
            "id": "swipe-1",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "base",
        "name": "boss_kill",
        "t": 1080
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1080,
          "magnitude": 1,
          "valence": "good",
          "importance": 1,
          "actor": "self",
          "target": "other",
          "outcome": "broke",
          "description": "player fells the boss",
          "gauges": [
            "enemy_health"
          ],
          "sound": "felled",
          "base": "boss_kill",
          "chain": {
            "id": "swipe-1",
            "step": "end"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1080,
          "id": "enemy_health",
          "value": 0,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      }
    ]
  },
  {
    "name": "swipe-blocked",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1000,
          "id": "blade-torso",
          "phase": "start",
          "value": 0.3,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1033,
          "id": "blade-torso",
          "phase": "update",
          "value": 0.9,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1050,
          "id": "blade-torso",
          "phase": "end",
          "value": 0.6,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_block",
        "t": 1080
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1080,
          "magnitude": 0.42857142857142855,
          "valence": "bad",
          "importance": 0.5,
          "actor": "other",
          "target": "self",
          "outcome": "blocked",
          "description": "enemy guard blocks player paper sword at torso",
          "gauges": [
            "enemy_guard"
          ],
          "sound": "enemy_block",
          "base": "enemy_block",
          "chain": {
            "id": "swipe-1",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1080,
          "id": "enemy_guard",
          "value": 0.6,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1080,
          "id": "enemy_health",
          "value": 0.97,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      }
    ]
  },
  {
    "name": "swipe-missed",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1000,
          "magnitude": 0,
          "valence": "neutral",
          "importance": 0.1,
          "actor": "self",
          "target": "other",
          "outcome": "missed",
          "description": "player blade misses enemy",
          "chain": {
            "id": "swipe-1",
            "step": "resolve"
          }
        }
      }
    ]
  },
  {
    "name": "swipe-parried",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1000,
          "id": "blade-torso",
          "phase": "start",
          "value": 0.3,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1033,
          "id": "blade-torso",
          "phase": "update",
          "value": 0.9,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1050,
          "id": "blade-torso",
          "phase": "end",
          "value": 0.6,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "parried",
        "t": 1080
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1080,
          "magnitude": 0.6,
          "valence": "bad",
          "importance": 0.7,
          "actor": "other",
          "target": "self",
          "outcome": "deflected",
          "description": "enemy counter stance parries player blade",
          "sound": "parried",
          "base": "parried",
          "chain": {
            "id": "swipe-1",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "clock",
          "clock": "expect",
          "t": 1080,
          "at": 1480,
          "description": "enemy winds up a slash attack",
          "importance": 0.6142857142857143,
          "chain": {
            "id": "attack-2",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1480,
          "magnitude": 0.35714285714285715,
          "actor": "other",
          "target": "self",
          "valence": "bad",
          "importance": 0.8,
          "outcome": "landed",
          "description": "enemy slash attack hits player",
          "gauges": [
            "health"
          ],
          "sound": "player_hit",
          "base": "player_hit",
          "chain": {
            "id": "attack-2",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "base",
        "name": "player_hit",
        "t": 1480
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1480,
          "id": "health",
          "value": 0.8,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      }
    ]
  },
  {
    "name": "swipe-held-back",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1000,
          "id": "blade-torso",
          "phase": "start",
          "value": 0.4,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1016,
          "id": "blade-torso",
          "phase": "end",
          "value": 0.36666666666666664,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1016,
          "magnitude": 0,
          "valence": "neutral",
          "importance": 0,
          "actor": "self",
          "target": "other",
          "outcome": "none",
          "description": "player swing is held back",
          "chain": {
            "id": "swipe-1",
            "step": "cancel"
          }
        }
      }
    ]
  },
  {
    "name": "burst-full",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "base",
        "name": "burst_start",
        "t": 1000
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1000,
          "magnitude": 0.7,
          "valence": "good",
          "importance": 0.8,
          "actor": "self",
          "target": "other",
          "outcome": "none",
          "description": "player unleashes paper-rending combo",
          "gauges": [
            "burst"
          ],
          "base": "burst_start",
          "chain": {
            "id": "burst-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "clock",
          "clock": "grid",
          "t": 1000,
          "interval": 180,
          "until": 1920,
          "chain": {
            "id": "burst-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1000,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "base",
        "name": "enemy_hit",
        "t": 1200
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1200,
          "magnitude": 0.2857142857142857,
          "valence": "good",
          "importance": 0.4,
          "actor": "self",
          "target": "other",
          "outcome": "landed",
          "description": "player paper-rending combo hits enemy with paper sword",
          "gauges": [
            "enemy_health"
          ],
          "sound": "hit_sword",
          "base": "enemy_hit",
          "chain": {
            "id": "burst-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_hit",
        "t": 1380
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1380,
          "magnitude": 0.2857142857142857,
          "valence": "good",
          "importance": 0.4,
          "actor": "self",
          "target": "other",
          "outcome": "landed",
          "description": "player paper-rending combo hits enemy with paper sword",
          "gauges": [
            "enemy_health"
          ],
          "sound": "hit_sword",
          "base": "enemy_hit",
          "chain": {
            "id": "burst-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_hit",
        "t": 1560
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1560,
          "magnitude": 0.2857142857142857,
          "valence": "good",
          "importance": 0.4,
          "actor": "self",
          "target": "other",
          "outcome": "landed",
          "description": "player paper-rending combo hits enemy with paper sword",
          "gauges": [
            "enemy_health"
          ],
          "sound": "hit_sword",
          "base": "enemy_hit",
          "chain": {
            "id": "burst-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_hit",
        "t": 1740
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1740,
          "magnitude": 0.2857142857142857,
          "valence": "good",
          "importance": 0.4,
          "actor": "self",
          "target": "other",
          "outcome": "landed",
          "description": "player paper-rending combo hits enemy with paper sword",
          "gauges": [
            "enemy_health"
          ],
          "sound": "hit_sword",
          "base": "enemy_hit",
          "chain": {
            "id": "burst-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_hit",
        "t": 1920
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1920,
          "magnitude": 0.2857142857142857,
          "valence": "good",
          "importance": 0.7,
          "actor": "self",
          "target": "other",
          "outcome": "landed",
          "description": "player paper-rending combo hits enemy with paper sword",
          "gauges": [
            "enemy_health"
          ],
          "sound": "hit_sword",
          "base": "enemy_hit",
          "chain": {
            "id": "burst-1",
            "step": "end"
          }
        }
      }
    ]
  },
  {
    "name": "burst-kill",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 0.1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "base",
        "name": "burst_start",
        "t": 1000
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1000,
          "magnitude": 0.7,
          "valence": "good",
          "importance": 0.8,
          "actor": "self",
          "target": "other",
          "outcome": "none",
          "description": "player unleashes paper-rending combo",
          "gauges": [
            "burst"
          ],
          "base": "burst_start",
          "chain": {
            "id": "burst-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "clock",
          "clock": "grid",
          "t": 1000,
          "interval": 180,
          "until": 1920,
          "chain": {
            "id": "burst-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_hit",
        "t": 1200
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1200,
          "magnitude": 0.2857142857142857,
          "valence": "good",
          "importance": 0.4,
          "actor": "self",
          "target": "other",
          "outcome": "landed",
          "description": "player paper-rending combo hits enemy with paper sword",
          "gauges": [
            "enemy_health"
          ],
          "sound": "hit_sword",
          "base": "enemy_hit",
          "chain": {
            "id": "burst-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_hit",
        "t": 1380
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1380,
          "magnitude": 0.2857142857142857,
          "valence": "good",
          "importance": 0.4,
          "actor": "self",
          "target": "other",
          "outcome": "landed",
          "description": "player paper-rending combo hits enemy with paper sword",
          "gauges": [
            "enemy_health"
          ],
          "sound": "hit_sword",
          "base": "enemy_hit",
          "chain": {
            "id": "burst-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_kill",
        "t": 1380
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1380,
          "magnitude": 0.6,
          "valence": "good",
          "importance": 0.8,
          "actor": "self",
          "target": "other",
          "outcome": "broke",
          "description": "player fells the enemy",
          "gauges": [
            "enemy_health"
          ],
          "sound": "felled",
          "base": "enemy_kill",
          "chain": {
            "id": "burst-1",
            "step": "end"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1380,
          "id": "enemy_health",
          "value": 0,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      }
    ]
  },
  {
    "name": "burst-cut-short",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "base",
        "name": "burst_start",
        "t": 1000
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1000,
          "magnitude": 0.7,
          "valence": "good",
          "importance": 0.8,
          "actor": "self",
          "target": "other",
          "outcome": "none",
          "description": "player unleashes paper-rending combo",
          "gauges": [
            "burst"
          ],
          "base": "burst_start",
          "chain": {
            "id": "burst-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "clock",
          "clock": "grid",
          "t": 1000,
          "interval": 180,
          "until": 1920,
          "chain": {
            "id": "burst-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_hit",
        "t": 1200
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1200,
          "magnitude": 0.2857142857142857,
          "valence": "good",
          "importance": 0.4,
          "actor": "self",
          "target": "other",
          "outcome": "landed",
          "description": "player paper-rending combo hits enemy with paper sword",
          "gauges": [
            "enemy_health"
          ],
          "sound": "hit_sword",
          "base": "enemy_hit",
          "chain": {
            "id": "burst-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1380,
          "magnitude": 0,
          "valence": "neutral",
          "importance": 0,
          "actor": "self",
          "target": "other",
          "outcome": "none",
          "description": "player burst is cut short",
          "chain": {
            "id": "burst-1",
            "step": "cancel"
          }
        }
      }
    ]
  },
  {
    "name": "attack-hit",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "clock",
          "clock": "expect",
          "t": 1000,
          "at": 1500,
          "description": "enemy winds up a slash attack",
          "importance": 0.6142857142857143,
          "chain": {
            "id": "attack-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1500,
          "magnitude": 0.35714285714285715,
          "actor": "other",
          "target": "self",
          "valence": "bad",
          "importance": 0.8,
          "outcome": "landed",
          "description": "enemy slash attack hits player",
          "gauges": [
            "health"
          ],
          "sound": "player_hit",
          "base": "player_hit",
          "chain": {
            "id": "attack-1",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "base",
        "name": "player_hit",
        "t": 1500
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1500,
          "id": "health",
          "value": 0.8,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      }
    ]
  },
  {
    "name": "attack-blocked",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "clock",
          "clock": "expect",
          "t": 1000,
          "at": 1500,
          "description": "enemy winds up a slash attack",
          "importance": 0.6142857142857143,
          "chain": {
            "id": "attack-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1500,
          "magnitude": 0.35714285714285715,
          "actor": "other",
          "target": "self",
          "valence": "good",
          "importance": 0.6,
          "outcome": "blocked",
          "description": "player shield blocks enemy slash attack",
          "gauges": [
            "shield"
          ],
          "sound": "player_block",
          "base": "player_block",
          "chain": {
            "id": "attack-1",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "base",
        "name": "player_block",
        "t": 1500
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1500,
          "id": "shield",
          "value": 0.6,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1500,
          "id": "health",
          "value": 0.97,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      }
    ]
  },
  {
    "name": "attack-shield-breaks",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 0.2,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "clock",
          "clock": "expect",
          "t": 1000,
          "at": 1500,
          "description": "enemy winds up a slash attack",
          "importance": 0.6142857142857143,
          "chain": {
            "id": "attack-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1500,
          "magnitude": 0.35714285714285715,
          "actor": "other",
          "target": "self",
          "valence": "good",
          "importance": 0.6,
          "outcome": "blocked",
          "description": "player shield blocks enemy slash attack",
          "gauges": [
            "shield"
          ],
          "sound": "player_block",
          "base": "player_block",
          "chain": {
            "id": "attack-1",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "base",
        "name": "player_block",
        "t": 1500
      },
      {
        "kind": "base",
        "name": "player_guard_break",
        "t": 1500
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1500,
          "magnitude": 0.8,
          "valence": "bad",
          "importance": 0.9,
          "actor": "other",
          "target": "self",
          "outcome": "broke",
          "description": "player shield breaks",
          "gauges": [
            "shield"
          ],
          "sound": "guard_break",
          "base": "player_guard_break",
          "chain": {
            "id": "attack-1",
            "step": "end"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1500,
          "id": "shield",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      }
    ]
  },
  {
    "name": "attack-countered",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "clock",
          "clock": "expect",
          "t": 1000,
          "at": 1500,
          "description": "enemy winds up a slash attack",
          "importance": 0.6142857142857143,
          "chain": {
            "id": "attack-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1500,
          "magnitude": 0.35714285714285715,
          "actor": "other",
          "target": "self",
          "valence": "good",
          "importance": 0.9,
          "outcome": "deflected",
          "description": "player shield perfectly counters enemy slash attack",
          "sound": "counter",
          "base": "counter",
          "chain": {
            "id": "attack-1",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "base",
        "name": "counter",
        "t": 1500
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1500,
          "id": "enemy_guard",
          "value": 0.5,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      }
    ]
  },
  {
    "name": "attack-dodge-countered",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "clock",
          "clock": "expect",
          "t": 1000,
          "at": 1500,
          "description": "enemy winds up a slash attack",
          "importance": 0.6142857142857143,
          "chain": {
            "id": "attack-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1500,
          "magnitude": 0.35714285714285715,
          "actor": "other",
          "target": "self",
          "valence": "good",
          "importance": 0.9,
          "outcome": "missed",
          "description": "player dodges enemy slash attack at the last instant",
          "sound": "counter",
          "base": "counter",
          "chain": {
            "id": "attack-1",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "base",
        "name": "counter",
        "t": 1500
      }
    ]
  },
  {
    "name": "attack-evaded",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "clock",
          "clock": "expect",
          "t": 1000,
          "at": 1500,
          "description": "enemy winds up a slash attack",
          "importance": 0.6142857142857143,
          "chain": {
            "id": "attack-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1500,
          "magnitude": 0.35714285714285715,
          "actor": "other",
          "target": "self",
          "valence": "good",
          "importance": 0.4,
          "outcome": "missed",
          "description": "player dodges enemy slash attack",
          "chain": {
            "id": "attack-1",
            "step": "resolve"
          }
        }
      }
    ]
  },
  {
    "name": "attack-interrupted",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "clock",
          "clock": "expect",
          "t": 1000,
          "at": 1500,
          "description": "enemy winds up a slash attack",
          "importance": 0.6142857142857143,
          "chain": {
            "id": "attack-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1100,
          "id": "blade-weaponHand",
          "phase": "start",
          "value": 0.3,
          "description": "player paper sword crosses enemy weaponHand",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-2",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1133,
          "id": "blade-weaponHand",
          "phase": "update",
          "value": 0.9,
          "description": "player paper sword crosses enemy weaponHand",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-2",
            "step": "progress"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1150,
          "id": "blade-weaponHand",
          "phase": "end",
          "value": 0.6,
          "description": "player paper sword crosses enemy weaponHand",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-2",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_hit",
        "t": 1180
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1180,
          "magnitude": 0.39285714285714285,
          "valence": "good",
          "importance": 0.5,
          "actor": "self",
          "target": "other",
          "outcome": "landed",
          "description": "player slashes enemy weaponHand with paper sword",
          "gauges": [
            "enemy_guard",
            "enemy_health"
          ],
          "sound": "hit_sword",
          "base": "enemy_hit",
          "chain": {
            "id": "swipe-2",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1180,
          "magnitude": 0,
          "valence": "neutral",
          "importance": 0,
          "actor": "other",
          "target": "self",
          "outcome": "none",
          "description": "enemy attack is called off",
          "chain": {
            "id": "attack-1",
            "step": "cancel"
          }
        }
      }
    ]
  },
  {
    "name": "enemy-guard-break",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 0.1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1000,
          "id": "blade-torso",
          "phase": "start",
          "value": 0.3,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1033,
          "id": "blade-torso",
          "phase": "update",
          "value": 0.9,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "stream",
          "t": 1050,
          "id": "blade-torso",
          "phase": "end",
          "value": 0.6,
          "description": "player paper sword crosses enemy torso",
          "actor": "self",
          "target": "other",
          "valence": "neutral",
          "importance": 0.2,
          "chain": {
            "id": "swipe-1",
            "step": "progress"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_block",
        "t": 1080
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1080,
          "magnitude": 0.42857142857142855,
          "valence": "bad",
          "importance": 0.5,
          "actor": "other",
          "target": "self",
          "outcome": "blocked",
          "description": "enemy guard blocks player paper sword at torso",
          "gauges": [
            "enemy_guard"
          ],
          "sound": "enemy_block",
          "base": "enemy_block",
          "chain": {
            "id": "swipe-1",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "base",
        "name": "enemy_guard_break",
        "t": 1080
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1080,
          "magnitude": 0.7,
          "valence": "good",
          "importance": 0.8,
          "actor": "self",
          "target": "other",
          "outcome": "broke",
          "description": "enemy guard breaks",
          "gauges": [
            "enemy_guard"
          ],
          "sound": "guard_break",
          "base": "enemy_guard_break"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "clock",
          "clock": "window",
          "t": 1080,
          "until": 3580,
          "description": "enemy is open to attack"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1080,
          "id": "enemy_guard",
          "value": 0,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      }
    ]
  },
  {
    "name": "player-death",
    "records": [
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "shield",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.34
          ],
          "description": "player shield durability"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_guard",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy guard"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "enemy_health",
          "value": 1,
          "goodWhen": "low",
          "owner": "other",
          "thresholds": [
            0.25
          ],
          "description": "enemy health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "burst",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "description": "player burst charge"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 0,
          "id": "health",
          "value": 0.1,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "clock",
          "clock": "expect",
          "t": 1000,
          "at": 1500,
          "description": "enemy winds up a slash attack",
          "importance": 0.6142857142857143,
          "chain": {
            "id": "attack-1",
            "step": "start"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1500,
          "magnitude": 0.35714285714285715,
          "actor": "other",
          "target": "self",
          "valence": "bad",
          "importance": 0.8,
          "outcome": "landed",
          "description": "enemy slash attack hits player",
          "gauges": [
            "health"
          ],
          "sound": "player_hit",
          "base": "player_hit",
          "chain": {
            "id": "attack-1",
            "step": "resolve"
          }
        }
      },
      {
        "kind": "base",
        "name": "player_hit",
        "t": 1500
      },
      {
        "kind": "base",
        "name": "player_death",
        "t": 1500
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "event",
          "t": 1500,
          "magnitude": 1,
          "valence": "bad",
          "importance": 1,
          "actor": "other",
          "target": "self",
          "outcome": "broke",
          "description": "player falls",
          "gauges": [
            "health"
          ],
          "base": "player_death",
          "chain": {
            "id": "attack-1",
            "step": "end"
          }
        }
      },
      {
        "kind": "signal",
        "signal": {
          "kind": "gauge",
          "t": 1500,
          "id": "health",
          "value": 0,
          "goodWhen": "high",
          "owner": "self",
          "thresholds": [
            0.3
          ],
          "description": "player health"
        }
      }
    ]
  }
];
