import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { SCENARIOS } from '../src/client/haptics/scenarios';

/**
 * Keeps the upscaler's signal fixtures in step with the game adapter. The
 * fixtures are generated from scripted scenarios into a typed module the
 * upscaler tests import; run with UPDATE_FIXTURES=1 to rewrite it after an
 * intended adapter change.
 */

const DIR = 'src/shared/upscaler/fixtures';
const FILE = `${DIR}/scenarios.ts`;
const text = `// Generated by tools/signalFixtures.test.mjs from src/client/haptics/scenarios.ts.
// Do not edit; run the tests with UPDATE_FIXTURES=1 instead.
import type { FixtureScenario } from './types';

export const SCENARIOS: readonly FixtureScenario[] = ${JSON.stringify(SCENARIOS, null, 2)};
`;

describe('signal fixtures', () => {
  if (process.env.UPDATE_FIXTURES) {
    mkdirSync(DIR, { recursive: true });
    writeFileSync(FILE, text);
  }

  it('match the adapter', () => {
    expect(existsSync(FILE)).toBe(true);
    expect(readFileSync(FILE, 'utf8').replace(/\r\n/g, '\n')).toBe(text);
  });

  it('every scenario closes every chain it opens', () => {
    for (const s of SCENARIOS) {
      const open = new Map();
      for (const r of s.records) {
        const chain = r.kind === 'signal' ? r.signal.chain : undefined;
        if (!chain) continue;
        if (chain.step === 'start') open.set(chain.id, true);
        if (['end', 'cancel'].includes(chain.step)) open.delete(chain.id);
        if (chain.step === 'resolve') open.set(chain.id, false);
      }
      const dangling = [...open]
        .filter(([, unresolved]) => unresolved)
        .map(([id]) => id);
      expect({ scenario: s.name, dangling }).toEqual({
        scenario: s.name,
        dangling: [],
      });
    }
  });

  it('pairs every base vibration with a signal naming it', () => {
    for (const s of SCENARIOS) {
      const bases = s.records
        .filter((r) => r.kind === 'base')
        .map((r) => r.name)
        .sort();
      const named = s.records
        .filter(
          (r) =>
            r.kind === 'signal' && r.signal.kind === 'event' && r.signal.base
        )
        .map((r) => r.signal.base)
        .sort();
      expect({ scenario: s.name, bases }).toEqual({
        scenario: s.name,
        bases: named,
      });
    }
  });
});
